##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

# Header
menu:
  - page: 首页
    directory: .
    icon: fa-home 
  - page: 代码
    directory: code/
    icon: fa-xie           
  - page: 归档
    directory: archives/
    icon: fa-archive
  - page: 简历
    directory: resume/
    icon: fa-fei 
  - page: 关于
    directory: about/
    icon: fa-user


# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  #- links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  uyan: ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)

#Share
baidu_share: true ## 百度分享
JiaThis_share: ##true ##JiaThis分享
duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

# About page
about:
  photo_url: http://m.qpic.cn/psb?/V14B1DnT4HLbyQ/RG*rNI5VQFeoTgXwGtilf0lf9Q5g1ExxzXuGI0weFxQ!/b/dDIBAAAAAAAA&bo=zADMAAAAAAARBzA!&rf=viewer_4
  items:
  - label: email
    icon: fa-email
    url: dqpiytu@163.com
    title: dqpiytu@163.com
  - label: github
    icon: fa-github
    url: https://github.com/yetongxue
    title: yetongxue
  - label: weibo
    icon: fa-weibo
    url: https://weibo.com/u/3932472768
    title: 早餐有蛋


# Links widget. Empty links will hide widget.
links:
  - title: site-name1
    url: http://www.example1.com/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/
